### PR TITLE
fix(#17): Monorepo sourcemap support

### PR DESCRIPTION
**Pull request by honerlaw**
### What does this PR do?

- add monorepo support by calling datadog-ci with npx instead of a relative path (see https://github.com/DataDog/expo-datadog/issues/17)
- explicitly add jest-watch-typeahead with exact version as another dependency was installing the latest version, which caused jest to fail to load the plugin and the tests would not run

### Motivation

I was using the recommended approach from issue 17 of using patch-package, and would prefer not to.

### Additional Notes

N/A

### Review checklist (to be filled by reviewers)

- [x] Feature or bugfix MUST have appropriate tests
- [x] Make sure you discussed the feature or bugfix with the maintaining team in an Issue
- [x] Make sure each commit and the PR mention the Issue number (cf the [CONTRIBUTING](CONTRIBUTING.md) doc)
- [x] If this PR is auto-generated, please make sure also to manually update the code related to the change

### Other

I am open to a different approach for handling this scenario.

### CODE REVIEW

**Comment by marco-saia-datadog** [comment]
Hi @honerlaw, thank you very much for your contribution! It looks really good at first glance, we will reach out soon with a proper review and perform some internal testing as well.

**Comment by honerlaw** [comment]
Hey @marco-saia-datadog I would say hold off on further testing at the moment, I have run into a few issues that need to be resolved first after further testing.

**Comment by marco-saia-datadog** [comment]
Hey @honerlaw! Thank you for the update, feel free to reach out at any moment

**Comment by marco-saia-datadog** [comment]
Hi @honerlaw!

We have decided to follow another approach, you can check it out in this PR: https://github.com/DataDog/expo-datadog/pull/38.

Thank you again for your time and your great contribution 🙏

**Pull request closed without merging**
